apiVersion: v1
kind: Pod
metadata:
  name: sgr-database
spec:
  containers:
  - name: sgr-database
    image: renandpf/sgr-database:1.0.0
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "senha"
