apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sgr-database
  name: sgr-database
spec:
  containers:
  - name: sgr-database
    image: renandpf/sgr-database:1.0.0
    ports:
      - containerPort: 3306
    envFrom:
      - configMapRef:
          name: sgr-database-mysql-cm