apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sgr-database
  name: sgr-database
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: senha
    image: renandpf/sgr-database:1.0.0
    name: sgr-database
    ports:
    - containerPort: 3306
