apiVersion: v1
kind: Pod
metadata:
  name: sgr-database
  #O label é usado para poder ser acessado por outros pods, services, etc (tipo DNS). Não da pra usar o "metadata.name". É recomendado sempre colocar
  labels:
    app: sgr-database
spec:
  containers:
  - name: sgr-database
    image: renandpf/sgr-database:1.0.0
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "senha"
