apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sgr-database
  name: sgr-database
spec:
  containers:
  - name: sgr-database
    image: renandpf/sgr-database:2.0.0
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sgr-database-mysql-secrets
            key: password